name: ci
on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: echo name
        run: echo "Meanrev"
  job2:
    runs-on: ubuntu-latest
    working-directory: workflowhello  
    steps:
      - name: checkout code 
        uses: actions/checkout@v4
      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: install dependencies
        run: npm install    
      - name: build react
        run: npm run build
