name: ci
on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: echo name
        run: echo "Meanrev"
